export const tableData = [
  { time: '8:00 - 8:55', cells: [
    { id: '2m1', selected: false },
    { id: '3m1', selected: false },
    { id: '4m1', selected: false },
    { id: '5m1', selected: false },
    { id: '6m1', selected: false },
    { id: '7m1', selected: false },
  ]},
  { time: '8:55 - 9:50', cells: [
    { id: '2m2', selected: false },
    { id: '3m2', selected: false },
    { id: '4m2', selected: false },
    { id: '5m2', selected: false },
    { id: '6m2', selected: false },
    { id: '7m2', selected: false },
  ]},
  { time: '10:00 - 10:55', cells: [
    { id: '2m3', selected: false },
    { id: '3m3', selected: false },
    { id: '4m3', selected: false },
    { id: '5m3', selected: false },
    { id: '6m3', selected: false },
    { id: '7m3', selected: false },
  ]},
  { time: '10:55 - 11:50', cells: [
    { id: '2m4', selected: false },
    { id: '3m4', selected: false },
    { id: '4m4', selected: false },
    { id: '5m4', selected: false },
    { id: '6m4', selected: false },
    { id: '7m4', selected: false },
  ]},
  { time: '12:00 - 12:55', cells: [
    { id: '2m5', selected: false },
    { id: '3m5', selected: false },
    { id: '4m5', selected: false },
    { id: '5m5', selected: false },
    { id: '6m5', selected: false },
    { id: '7m5', selected: false },
  ]},
  { time: '12:55 - 13:50', cells: [
    { id: '2t1', selected: false },
    { id: '3t1', selected: false },
    { id: '4t1', selected: false },
    { id: '5t1', selected: false },
    { id: '6t1', selected: false },
    { id: '7t1', selected: false },
  ]},
  { time: '14:00 - 14:55', cells: [
    { id: '2t2', selected: false },
    { id: '3t2', selected: false },
    { id: '4t2', selected: false },
    { id: '5t2', selected: false },
    { id: '6t2', selected: false },
    { id: '7t2', selected: false },
  ]},
  { time: '14:55 - 15:50', cells: [
    { id: '2t3', selected: false },
    { id: '3t3', selected: false },
    { id: '4t3', selected: false },
    { id: '5t3', selected: false },
    { id: '6t3', selected: false },
    { id: '7t3', selected: false },
  ]},
  { time: '16:00 - 16:55', cells: [
    { id: '2t4', selected: false },
    { id: '3t4', selected: false },
    { id: '4t4', selected: false },
    { id: '5t4', selected: false },
    { id: '6t4', selected: false },
    { id: '7t4', selected: false },
  ]},
  { time: '16:55 - 17:50', cells: [
    { id: '2t5', selected: false },
    { id: '3t5', selected: false },
    { id: '4t5', selected: false },
    { id: '5t5', selected: false },
    { id: '6t5', selected: false },
    { id: '7t5', selected: false },
  ]},
  { time: '18:00 - 18:55', cells: [
    { id: '2t6', selected: false },
    { id: '3t6', selected: false },
    { id: '4t6', selected: false },
    { id: '5t6', selected: false },
    { id: '6t6', selected: false },
    { id: '7t6', selected: false },
  ]},
  { time: '19:00 - 19:55', cells: [
    { id: '2n1', selected: false },
    { id: '3n1', selected: false },
    { id: '4n1', selected: false },
    { id: '5n1', selected: false },
    { id: '6n1', selected: false },
    { id: '7n1', selected: false },
  ]},
  { time: '19:55 - 20:50', cells: [
    { id: '2n2', selected: false },
    { id: '3n2', selected: false },
    { id: '4n2', selected: false },
    { id: '5n2', selected: false },
    { id: '6n2', selected: false },
    { id: '7n2', selected: false },
  ]},
  { time: '21:00 - 21:55', cells: [
    { id: '2n3', selected: false },
    { id: '3n3', selected: false },
    { id: '4n3', selected: false },
    { id: '5n3', selected: false },
    { id: '6n3', selected: false },
    { id: '7n3', selected: false },
  ]},
  { time: '21:55 - 22:50', cells: [
    { id: '2n4', selected: false },
    { id: '3n4', selected: false },
    { id: '4n4', selected: false },
    { id: '5n4', selected: false },
    { id: '6n4', selected: false },
    { id: '7n4', selected: false },
  ]},
];